spring.application.name=CodeLab

spring.profiles.active=local

# Server
server.servlet.context-path=/code-lab
server.port=7777

# JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle DB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Mybatis
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.config-location=classpath:mybatis-config.xml

# Mail - SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp

# Mail - Authentication / TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Mail - Encoding
spring.mail.default-encoding=UTF-8

# Multipart File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB






