-- =============== CREATE SEQUENCE ============
    CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
-- =============== CREATE TABLE ===============
    CREATE TABLE MEMBER (
        MEMBER_NO NUMBER, 
        USER_ID VARCHAR2(20) NOT NULL,
        NICK_NAME VARCHAR2(30) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        
        CONSTRAINT PK_MEMBER        PRIMARY KEY (MEMBER_NO),
        CONSTRAINT UQ_MEMBER_ID     UNIQUE (USER_ID)
    );
    
    