-- =============== CREATE SEQUENCE ============
    CREATE SEQUENCE SEQ_BOARD_CATEGORY_NO NOCACHE;
-- =============== CREATE TABLE ===============
    CREATE TABLE BOARD_CATEGORY (
        CATEGORY_NO NUMBER,
        CATEGORY_NAME VARCHAR2(30) NOT NULL,
        
        CONSTRAINT PK_BC PRIMARY KEY (CATEGORY_NO),
        CONSTRAINT UQ_BC_NAME UNIQUE (CATEGORY_NAME)
    );

