-- =============== CREATE SEQUENCE ============
    CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;
-- =============== CREATE TABLE ===============
    CREATE TABLE BOARD (
        BOARD_NO NUMBER,
        TITLE VARCHAR2(100) NOT NULL,
        CONTENT CLOB NOT NULL,
        CATEGORY_NO NUMBER NOT NULL,
        MEMBER_NO NUMBER NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        
        CONSTRAINT PK_BOARD          PRIMARY KEY (BOARD_NO),
        CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) 
                                     REFERENCES BOARD_CATEGORY (CATEGORY_NO),
        CONSTRAINT FK_BOARD_MEMBER   FOREIGN KEY (MEMBER_NO) 
                                     REFERENCES MEMBER (MEMBER_NO),
        CONSTRAINT CK_BOARD_STATUS   CHECK (STATUS IN('Y', 'N'))
    );

