-- =============== CREATE SEQUENCE ============
    CREATE SEQUENCE SEQ_BOARD_REPLY_NO NOCACHE;
-- =============== CREATE TABLE ===============
    CREATE TABLE BOARD_REPLY(
        REPLY_NO NUMBER,
        BOARD_NO NUMBER NOT NULL,
        MEMBER_NO  NUMBER NOT NULL,
        REPLY_CONTENT VARCHAR2(500) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        
        CONSTRAINT PK_BR            PRIMARY KEY (REPLY_NO),
        CONSTRAINT FK_BR_BOARD      FOREIGN KEY (BOARD_NO)
                                    REFERENCES BOARD (BOARD_NO),
        CONSTRAINT FK_BR_MEMBER     FOREIGN KEY (MEMBER_NO)
                                    REFERENCES MEMBER (MEMBER_NO),
        CONSTRAINT CK_BR_STATUS     CHECK (STATUS IN ('Y', 'N'))
    );

