
-- =============== RENAME SEQUENCES =================
RENAME SEQ_MEMBER_NO TO SEQ_MEMBER;
RENAME SEQ_BOARD_CATEGORY_NO TO SEQ_BOARD_CATEGORY;
RENAME SEQ_BOARD_NO TO SEQ_BOARD;
RENAME SEQ_BOARD_REPLY_NO TO SEQ_BOARD_REPLY;