-- =============== ADD COLUMN TO BOARD_CATEGORY  ===============
ALTER TABLE BOARD_CATEGORY ADD STATUS VARCHAR2(1) 
            DEFAULT 'Y' NOT NULL;
ALTER TABLE BOARD_CATEGORY ADD CREATED_AT DATE 
            DEFAULT SYSDATE NOT NULL;
ALTER TABLE BOARD_CATEGORY ADD UPDATED_AT DATE 
            DEFAULT SYSDATE NOT NULL;

ALTER TABLE BOARD_CATEGORY ADD CONSTRAINT CK_BC_STATUS CHECK (STATUS IN ('Y', 'N'));           
COMMENT ON COLUMN BOARD_CATEGORY.STATUS IS '카테고리 사용 여부(Y/N)';
COMMENT ON COLUMN BOARD.STATUS IS '게시글 사용 여부(Y/N)';
COMMENT ON COLUMN BOARD_REPLY.STATUS IS '댓글 사용 여부(Y/N)';

