-- =============== CREATE SEQUENCE ============
CREATE SEQUENCE SEQ_QUESTION NOCACHE;

-- =============== CREATE TABLE ===============
CREATE TABLE QUESTION (
    QUESTION_NO NUMBER,
    SUBJECT VARCHAR2(100),
    KEYWORD VARCHAR2(300) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_QUESTION PRIMARY KEY (QUESTION_NO)
);
