-- =============== CREATE SEQUENCE ============
CREATE SEQUENCE SEQ_ANSWER NOCACHE;

-- =============== CREATE TABLE ===============
CREATE TABLE ANSWER (
    ANSWER_NO NUMBER,
    QUESTION_NO NUMBER NOT NULL,
    ANSWER_CONTENT VARCHAR2(300) NOT NULL,

    CONSTRAINT PK_ANSWER PRIMARY KEY (ANSWER_NO),
    CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (QUESTION_NO)
                                   REFERENCES QUESTION (QUESTION_NO)
);
