-- =============== CREATE SEQUENCE ============
CREATE SEQUENCE SEQ_ATTEMPT NOCACHE;

-- =============== CREATE TABLE ===============
CREATE TABLE ATTEMPT (
    ATTEMPT_NO NUMBER,
    QUESTION_NO NUMBER NOT NULL,
    INPUT_ANSWER VARCHAR2(300) NOT NULL,
    IS_CORRECT CHAR(1) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_ATTEMPT PRIMARY KEY (ATTEMPT_NO),
    CONSTRAINT FK_ATTEMPT_QUESTION FOREIGN KEY (QUESTION_NO)
                                    REFERENCES QUESTION (QUESTION_NO),
    CONSTRAINT CK_ATTEMPT_IS_CORRECT CHECK (IS_CORRECT IN ('Y', 'N'))
);
