-- =============== DROP TABLE =================
    DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
    DROP TABLE BOARD CASCADE CONSTRAINTS;
    DROP TABLE BOARD_CATEGORY CASCADE CONSTRAINTS;
    DROP TABLE MEMBER CASCADE CONSTRAINTS;
-- =============== DROP SEQUENCE ==============
    DROP SEQUENCE SEQ_MEMBER;
    DROP SEQUENCE SEQ_BOARD_CATEGORY;
    DROP SEQUENCE SEQ_BOARD;
    DROP SEQUENCE SEQ_BOARD_REPLY;
-- =============== CREATE SEQUENCE ============
    CREATE SEQUENCE SEQ_MEMBER NOCACHE;
    CREATE SEQUENCE SEQ_BOARD_CATEGORY NOCACHE;
    CREATE SEQUENCE SEQ_BOARD NOCACHE;
    CREATE SEQUENCE SEQ_BOARD_REPLY NOCACHE;
-- =============== CREATE TABLE ===============
    CREATE TABLE MEMBER (
        MEMBER_NO NUMBER, 
        USER_ID VARCHAR2(20) NOT NULL,
        NICK_NAME VARCHAR2(30) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        
        CONSTRAINT PK_MEMBER        PRIMARY KEY (MEMBER_NO),
        CONSTRAINT UQ_MEMBER_ID     UNIQUE (USER_ID)
    );
    
    CREATE TABLE BOARD_CATEGORY (
        CATEGORY_NO NUMBER,
        CATEGORY_NAME VARCHAR2(30) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        
        CONSTRAINT PK_BC PRIMARY KEY (CATEGORY_NO),
        CONSTRAINT UQ_BC_NAME UNIQUE (CATEGORY_NAME),
        CONSTRAINT CK_BC_STATUS CHECK (STATUS IN ('Y','N'))
    );
    
    CREATE TABLE BOARD (
        BOARD_NO NUMBER,
        TITLE VARCHAR2(100) NOT NULL,
        CONTENT CLOB NOT NULL,
        CATEGORY_NO NUMBER NOT NULL,
        MEMBER_NO NUMBER NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        
        CONSTRAINT PK_BOARD          PRIMARY KEY (BOARD_NO),
        CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) 
                                     REFERENCES BOARD_CATEGORY (CATEGORY_NO),
        CONSTRAINT FK_BOARD_MEMBER   FOREIGN KEY (MEMBER_NO) 
                                     REFERENCES MEMBER (MEMBER_NO),
        CONSTRAINT CK_BOARD_STATUS   CHECK (STATUS IN('Y', 'N'))
    );
    
    CREATE TABLE BOARD_REPLY(
        REPLY_NO NUMBER,
        BOARD_NO NUMBER NOT NULL,
        MEMBER_NO  NUMBER NOT NULL,
        REPLY_CONTENT VARCHAR2(500) NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        
        CONSTRAINT PK_BR            PRIMARY KEY (REPLY_NO),
        CONSTRAINT FK_BR_BOARD      FOREIGN KEY (BOARD_NO)
                                    REFERENCES BOARD (BOARD_NO),
        CONSTRAINT FK_BR_MEMBER     FOREIGN KEY (MEMBER_NO)
                                    REFERENCES MEMBER (MEMBER_NO),
        CONSTRAINT CK_BR_STATUS     CHECK (STATUS IN ('Y', 'N'))
    );
-- =============== COMMENT ON COLUMN ===============
COMMENT ON COLUMN BOARD_CATEGORY.STATUS IS '카테고리 사용 여부(Y/N)';
COMMENT ON COLUMN BOARD.STATUS IS '게시글 사용 여부(Y/N)';
COMMENT ON COLUMN BOARD_REPLY.STATUS IS '댓글 사용 여부(Y/N)';

    
    
    
    
    
    